USE toastmasters;
CREATE TABLE future_meetings ( dayof       DATE PRIMARY KEY,
                               toastmaster INTEGER REFERENCES members,
                               topicmaster INTEGER REFERENCES members,
                               geneval     INTEGER REFERENCES members,
                               grammarian  INTEGER REFERENCES members,
                               votecounter INTEGER REFERENCES members,
                               ahcounter   INTEGER REFERENCES members,
                               jokemaster  INTEGER REFERENCES members,
                               listener    INTEGER REFERENCES members,
                               momenttm    INTEGER REFERENCES members,
                               speaker1    INTEGER REFERENCES members,
                               speaker2    INTEGER REFERENCES members,
                               speaker3    INTEGER REFERENCES members,
                               eval1       INTEGER REFERENCES members,
                               eval2       INTEGER REFERENCES members,
                               eval3       INTEGER REFERENCES members,
                               timer       INTEGER REFERENCES members );
